import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Post from './Post'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hello world</h1>
        <button>press this</button>
        <br></br>
        <Post></Post>
      </main>
    </div>
  )
}
